version: 0.2

phases:
  install:
    commands:
      - echo "Fase de instalação - Atualizando pacotes"
      - yum update -y
  pre_build:
    commands:
      - echo "Fase de pré-build - Clonando repositório (automático pelo CodeBuild)"
      - echo "Preparando para gerar a página HTML"
  build:
    commands:
      - echo "Fase de build - Criando página HTML"
      - echo "<!DOCTYPE html><html><head><title>Teste CodeBuild</title></head><body><h1>Build concluído com sucesso!</h1><p>Esta página foi gerada automaticamente pelo AWS CodeBuild.</p></body></html>" > index.html
  post_build:
    commands:
      - echo "Fase de pós-build - Commitando e enviando alterações para o GitHub"
      #- git add index.html
      #- git commit -m "Adicionando página HTML gerada pelo CodeBuild"
      #- git push
artifacts:
  files:
    - index.html
